services:
  web-botsoncom:
    build:
      context: ..
      dockerfile: http.Dockerfile
      network: host    # <-- AFEGEIX AQUESTA LÍNIA AQUÍ
    container_name: web-dck-botsoncom
    network_mode: "host"
    volumes:
      - ../html:/var/www/botson
      - ../imatges:/srv/www/botson/imatges